name: Build

on:

  workflow_dispatch:

  push:

  pull_request:




permissions:
  contents: write  #publish release


jobs:

  build_mac_x86:
    strategy:
      fail-fast: false
      matrix:
        config: [ Release, Debug ]
    runs-on: macos-latest
    name: "x86_64 macos ${{ matrix.config }}"
    steps:
      - name: Install Dependencies
        run: |
          brew install cmake conan
      - uses: actions/checkout@v3
      - name: Run on architecture
        run: |
          conan profile detect
          conan install conanfile.txt --build=missing -r conancenter --deployer full_deploy --output-folder out
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ffmpeg-x86_64-macos-${{ matrix.config }}
          path: out/**/*.*
          if-no-files-found: error

  vendor_package:
    needs:
      - build_mac_x86
#      - build_mac_arm64
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/download-artifact@v3.0.2
      with:
        path: ffmpeg
    - uses: actions/upload-artifact@v3.1.2
      with:
        name: ffmpeg_vendor_package_all_builds
        path: ffmpeg
        if-no-files-found: error
    - run: 7z a -tzip ffmpeg.zip ffmpeg
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifactErrorsFailBuild: true
        artifacts: ffmpeg.zip
        prerelease: false
        replacesArtifacts: true
        tag: FFMPEG-VER-2-12-1_${{ github.run_number }}-${{ github.run_attempt }}
        allowUpdates: true
